question_data = [
    {"category": "Science: Computers",
     "type": "boolean",
     "difficulty": "medium",
     "question": "The common software-programming acronym &quot;I18N&quot; comes from the term &quot;Interlocalization&quot;.",
     "correct_answer": "False",
     "incorrect_answers": ["True"]},
    {"category": "Science: Computers",
     "type": "boolean",
     "difficulty": "medium",
     "question": "FLAC stands for &quot;Free Lossless Audio Condenser&quot;&#039;",
     "correct_answer": "False",
     "incorrect_answers": ["True"]},
    {"category": "Science: Computers",
     "type": "boolean",
     "difficulty": "easy",
     "question": "Linus Torvalds created Linux and Git.",
     "correct_answer": "True",
     "incorrect_answers": ["False"]},
    {"category": "Science: Computers",
     "type": "boolean",
     "difficulty": "easy",
     "question": "RAM stands for Random Access Memory.",
     "correct_answer": "True",
     "incorrect_answers": ["False"]},
    {"category": "Science: Computers",
     "type": "boolean",
     "difficulty": "easy",
     "question": "Ada Lovelace is often considered the first computer programmer.",
     "correct_answer": "True",
     "incorrect_answers": ["False"]},
    {"category": "Science: Computers",
     "type": "boolean",
     "difficulty": "medium",
     "question": "MacOS is based on Linux.",
     "correct_answer": "False",
     "incorrect_answers": ["True"]},
    {"category": "Science: Computers",
     "type": "boolean",
     "difficulty": "hard",
     "question": "The IBM PC used an Intel 8008 microprocessor clocked at 4.77 MHz and 8 kilobytes of memory.",
     "correct_answer": "False",
     "incorrect_answers": ["True"]},
    {"category": "Science: Computers",
     "type": "boolean",
     "difficulty": "easy",
     "question": "The Windows 7 operating system has six main editions.",
     "correct_answer": "True",
     "incorrect_answers": ["False"]},
    {"category": "Science: Computers",
     "type": "boolean",
     "difficulty": "medium",
     "question": "The first dual-core CPU was the Intel Pentium D.",
     "correct_answer": "False",
     "incorrect_answers": ["True"]},
    {"category": "Science: Computers",
     "type": "boolean",
     "difficulty": "medium",
     "question": "It&#039;s not possible to format a write-protected DVD-R Hard Disk.",
     "correct_answer": "True",
     "incorrect_answers": ["False"]},
    {"category": "Science: Computers",
     "type": "boolean",
     "difficulty": "medium",
     "question": "Android versions are named in alphabetical order.",
     "correct_answer": "True",
     "incorrect_answers": ["False"]},
    {"category": "Science: Computers",
     "type": "boolean",
     "difficulty": "medium",
     "question": "A Boolean value of &quot;0&quot; represents which of these words?",
     "correct_answer": "False",
     "incorrect_answers": ["True"]}
]
